### ISSUE TITLE
Don't require by default DRF_RECAPTCHA_SECRET_KEY

### ISSUE THREAD

**Issue by llybin** [llybin/drf-recaptcha#32]

**Comment by btimby** [comment]
At least add the error to the django check system so that it can be silenced. In my situation, I have ancillary containers that have no need of this library at run time (for example for running migrations, celery). I pull the key from the environment and would prefer to only provide it on containers that require it.

**Comment by btimby** [comment]
https://github.com/llybin/drf-recaptcha/pull/33
